package com.gnoemes.shikimori.entity.app.domain

enum class AnalyticEvent {
    PLAYER_OPENED_WEB,
    PLAYER_OPENED_EMBEDDED,
    PLAYER_OPENED_EXTERNAL,

    NAVIGATION_BOTTOM_MORE,
    NAVIGATION_BOTTOM_MAIN,
    NAVIGATION_BOTTOM_SEARCH,
    NAVIGATION_BOTTOM_CALENDAR,
    NAVIGATION_BOTTOM_RATES,
    NAVIGATION_DETAILS_ANIME,
    NAVIGATION_DETAILS_MANGA,
    NAVIGATION_DETAILS_RANOBE,
    NAVIGATION_DETAILS_CHARACTER,
    NAVIGATION_DETAILS_USER,
    NAVIGATION_DETAILS_PERSON,
    NAVIGATION_DETAILS_TOPIC,
    NAVIGATION_DETAILS_CLUB,
    NAVIGATION_WEB,
    NAVIGATION_SETTINGS,
    NAVIGATION_AUTHORIZATION,
    NAVIGATION_TOPIC_LIST,
    NAVIGATION_ANIME_EPISODES,
    NAVIGATION_ANIME_TRANSLATIONS,
    NAVIGATION_USER_HISTORY,
    NAVIGATION_USER_BANS,
    NAVIGATION_USER_FRIENDS,
    NAVIGATION_USER_CLUBS,
    NAVIGATION_USER_FAVORITES;

    override fun toString(): String = super.toString().toLowerCase()
}
